### ISSUE TITLE
cli-lantern crashes after startup

### ISSUE THREAD

**Issue by JamesOlvertone** [zlatinb/muwire#111]
Starting:
java -jar cli-lanterna-0.8.10-all.jar 
after setup (did a fresh one, no older config dir is there ) it tries to connect to the local i2prouter but fails:
                                                                        
`Exception in thread "main" groovy.lang.MissingPropertyException: No such property: hosts for class: com.muwire.core.hostcache.H2HostCache                                                                                                                                         
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)                                                                                               
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)                                                                   
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)                                                                                      
        at com.muwire.clilanterna.MainWindowView.refreshStats(MainWindowView.groovy:293)                                                                                                         
        at com.muwire.clilanterna.MainWindowView.<init>(MainWindowView.groovy:172)                                                                                                               
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                                              
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                                                                       
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                               
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)                                                                                                             
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)                                                                                                    
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)                                                        
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)                                                                                      
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)                                                                                      
        at com.muwire.clilanterna.CliLanterna.main(CliLanterna.groovy:169)                                                                                                                       
 `

It is still running but I don't  know what it is doing, is it still connecting? 
I open I2prouter console in browser and no connected muWire appears there.
Aborting with Ctrl-C.

**Comment by zlatinb** [comment]
Yes, this is because as I explained in #110 I've only been updating `cli-lanterna` just so that it can compile.  It is not trying to connect, it's crashed.

**Comment by JamesOlvertone** [comment]
I see, I read 110 too. Thank you for explaining this.
No I am not really interested in developing this lanterna based thing. I only was curious how complex the "gui" is, more like a dashboard for observing whats going on or comparable with the Swing-GUI-Version.

Are there plans to separte the muWire functionality from the frontend, like mldonkey did it?

Swing, cli, plugin, they all come with their own core. Sometimes you want to use a Webfrontend, sometimes a GUI or even a terminal console. muWire as a daemon would be nice with an interface to remote-control and observe it.

**Comment by zlatinb** [comment]
I think the latest version of the cli that worked was 0.7.0, if you're curious to see what it looks like you can try building from that tag.  It does have search, download and share functionality, but I built it as more of an experiment so it's not super user-friendly.

As far as splitting the core into a daemon, that's possible but a bit complicated.  The user would need to run 3 processes in order to use MuWire - an I2P[d] router, the MuWire core and one or more front-ends.  I don't have any concrete plans to implement such functionality atm, but that may change if there is sufficient demand so to speak.
