### ISSUE TITLE
Help running MuWire (or figuring out how to run an I2Prouter from source)

### ISSUE THREAD

**Issue by gubatron** [zlatinb/muwire#15]
git cloned, built the shadow gui, unzipped it, altered the generated `gui` script and passed it "-DembeddedRouter=true`, but it won't start, I get this:

```bash
$ ./gui
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/gubatron/workspace.frostwire/muwire/gui/build/distributions/gui-shadow-0.4.11/lib/gui-0.4.11.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Griffon 2.15.1
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Build: 2018-11-06T14:02:08.126+0100
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Revision: d5445b6e60e92ba6fe635ce9fe695c4b498f5ae7
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - JVM: 12.0.2 (Oracle Corporation 12.0.2+10)
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - OS: Mac OS X 10.14.6 x86_64
[main] INFO griffon.util.AnnotationUtils - resource bundle loader class with instance org.codehaus.griffon.runtime.util.ClassResourceBundleLoader@410ae9a3 evicted by org.codehaus.griffon.runtime.groovy.util.GroovyScriptResourceBundleLoader@319988b0
Sep 14, 2019 2:08:50 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: Loading home dir
Sep 14, 2019 2:08:50 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: will try default lnfs
[main] INFO griffon.swing.SwingGriffonApplication - Initializing all startup groups: [EventList, MainFrame]
[main] WARN org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager - Property 'application' in model (com.muwire.gui.EventListModel) must be annotated with @griffon.inject.MVCMember.
[main] WARN org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager - Property 'application' in model (com.muwire.gui.MainFrameModel) must be annotated with @griffon.inject.MVCMember.
[main] WARN org.codehaus.griffon.runtime.core.mvc.DefaultMVCGroupManager - Property 'application' in controller (com.muwire.gui.MainFrameController) must be annotated with @griffon.inject.MVCMember.
Sep 14, 2019 2:08:52 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: starting core services
Sep 14, 2019 2:08:52 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: loading existing props file
Sep 14, 2019 2:08:52 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: Initializing I2P context
Sep 14, 2019 2:08:52 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: initializing I2P socket manager
Sep 14, 2019 2:08:52 PM com.muwire.core.util.JULLog log
INFO: Resource name [libjbigi-osx-none_64.jnilib] was not found
Sep 14, 2019 2:08:52 PM com.muwire.core.util.JULLog log
INFO: Resource name [libjbigi-osx-none.jnilib] was not found
Sep 14, 2019 2:08:52 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
WARNING: Native BigInteger library jbigi not loaded - using pure Java - poor performance may result - see http://i2p-projekt.i2p/jbigi for help
Sep 14, 2019 2:08:52 PM com.muwire.core.util.JULLog log
INFO: [MuWire(INIT)]: Change state to OPENING
Sep 14, 2019 2:08:52 PM com.muwire.core.util.JULLog log
INFO: [MuWire(OPENING)]: Change state to CLOSING
Sep 14, 2019 2:08:52 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: [MuWire(CLOSING)]: Closing the socket
java.lang.Exception: closeSocket
	at net.i2p.client.impl.I2PSessionImpl.closeSocket(I2PSessionImpl.java:1331)
	at net.i2p.client.impl.I2PSessionImpl.connect(I2PSessionImpl.java:848)
	at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:415)
	at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:301)
	at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:276)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at com.muwire.core.Core$_closure4.doCall(Core.groovy:168)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1215)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1699)
	at org.codehaus.groovy.runtime.dgm$1020.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at com.muwire.core.Core.<init>(Core.groovy:167)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at Ready.execute(Ready.groovy:97)
	at org.codehaus.griffon.runtime.core.DefaultApplicationConfigurer.runLifecycleHandler(DefaultApplicationConfigurer.java:111)
	at org.codehaus.griffon.runtime.core.AbstractGriffonApplication.ready(AbstractGriffonApplication.java:275)
	at org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper.run(AbstractApplicationBootstrapper.java:92)
	at org.codehaus.griffon.runtime.core.AbstractGriffonApplication.run(AbstractGriffonApplication.java:99)
	at griffon.swing.SwingGriffonApplication.main(SwingGriffonApplication.java:78)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at com.muwire.gui.Launcher.main(Launcher.groovy:8)

Sep 14, 2019 2:08:52 PM com.muwire.core.util.JULLog log
INFO: [MuWire(CLOSING)]: Change state to CLOSING
Sep 14, 2019 2:08:52 PM com.muwire.core.util.JULLog log
INFO: [MuWire(CLOSING)]: Change state to CLOSED
Sep 14, 2019 2:08:52 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
SEVERE: Error creating session for socket manager
net.i2p.client.I2PSessionException: [MuWire(OPENING)]: Cannot connect to the router on 127.0.0.1:7654 and build tunnels
	at net.i2p.client.impl.I2PSessionImpl.connect(I2PSessionImpl.java:837)
	at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:415)
	at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:301)
	at net.i2p.client.streaming.I2PSocketManagerFactory.createManager(I2PSocketManagerFactory.java:276)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at com.muwire.core.Core$_closure4.doCall(Core.groovy:168)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1215)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1699)
	at org.codehaus.groovy.runtime.dgm$1020.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at com.muwire.core.Core.<init>(Core.groovy:167)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at Ready.execute(Ready.groovy:97)
	at org.codehaus.griffon.runtime.core.DefaultApplicationConfigurer.runLifecycleHandler(DefaultApplicationConfigurer.java:111)
	at org.codehaus.griffon.runtime.core.AbstractGriffonApplication.ready(AbstractGriffonApplication.java:275)
	at org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper.run(AbstractApplicationBootstrapper.java:92)
	at org.codehaus.griffon.runtime.core.AbstractGriffonApplication.run(AbstractGriffonApplication.java:99)
	at griffon.swing.SwingGriffonApplication.main(SwingGriffonApplication.java:78)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at com.muwire.gui.Launcher.main(Launcher.groovy:8)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at net.i2p.client.impl.I2PSessionImpl.connect(I2PSessionImpl.java:748)
	... 29 more

Sep 14, 2019 2:08:52 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
SEVERE: couldn't initialize core
java.lang.NullPointerException: Cannot invoke method getDefaultOptions() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:164)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at com.muwire.core.Core.<init>(Core.groovy:170)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at Ready.execute(Ready.groovy:97)
	at org.codehaus.griffon.runtime.core.DefaultApplicationConfigurer.runLifecycleHandler(DefaultApplicationConfigurer.java:111)
	at org.codehaus.griffon.runtime.core.AbstractGriffonApplication.ready(AbstractGriffonApplication.java:275)
	at org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper.run(AbstractApplicationBootstrapper.java:92)
	at org.codehaus.griffon.runtime.core.AbstractGriffonApplication.run(AbstractGriffonApplication.java:99)
	at griffon.swing.SwingGriffonApplication.main(SwingGriffonApplication.java:78)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at com.muwire.gui.Launcher.main(Launcher.groovy:8)
```

So I thought, well, I'll just have to run my own I2P router, what the hell.

I cloned I2P, did `gradle assemble`, but then there's no clear way on how to run it and the god damn instructions and website talk too much shit and don't tell you what do do right after `gradle assemble`.

I start grepping and I find this `sh` script:
`./installer/resources/i2prouter`

I try:
```
$ sh
sh-3.2$ source ./installer/resources/i2prouter
Starting I2P Failed: Unable to find %INSTALL_PATH/wrapper.config
```

FML

I see that there's a "wrapper.config" on that same folder
```
sh-3.2$ cd installer/resources
sh-3.2$ chmod. +x i2prouter #make the sob executable
sh-3.2$ export INSTALL_PATH=`pwd` #make this folder the damn path
sh-3.2$ ./i2prouter
Starting I2P Failed: Unable to find %INSTALL_PATH/wrapper.config
```

FML

**Comment by gubatron** [comment]
maybe "sh" is different than bash, let's see:
```
sh-3.2$ export %INSTALL_PATH=`pwd`
sh: export: `%INSTALL_PATH=/Users/gubatron/workspace.frostwire/i2p.i2p/installer/resources': not a valid identifier
```

nope.

**Comment by zlatinb** [comment]
Building your own router with gradle doesn't fully work.  Do the following:
`
ant clean pkg
`
And then run `java -jar install.jar` which will install the i2p router on your system.

As far as running the embedded router, I don't recommend hacking the run script; instead try typing `java -DembeddedRouter=true -jar gui-shadow-x.y.z.jar` although that will fail to connect to the i2p network as the reseed certificates are not included in this source code.  So if you just want to give it a quick try grab a binary from https://muwire.com or do the external i2p router build as described above.

**Comment by gubatron** [comment]
guess I'll have to just get the binary, started having issues with `ant clean pkg` and gettext's msgfmt failing to build.
