### ISSUE TITLE
Rightclicking user in Trusted tab and selecting Browse or Browse Collection: exception everytime

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#158]
This happens:

```
griffon.exceptions.InstanceMethodInvocationException: An error occurred while invoking instance method com.muwire.gui.MainFrameController.browseFromTrusted()
	at griffon.util.GriffonClassUtils.invokeExactInstanceMethod(GriffonClassUtils.java:3186)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at jdk.proxy2/jdk.proxy2.$Proxy31.invokeAction(Unknown Source)
	at griffon.swing.support.SwingAction.actionPerformed(SwingAction.java:79)
	at com.jtattoo.plaf.BaseButtonListener.mouseReleased(BaseButtonListener.java:65)
Caused by: groovy.lang.MissingMethodException: No signature of method: com.muwire.gui.MainFrameView.getSelectedContactsTableRow() is applicable for argument types: () values: []
Possible solutions: getSelectedContactsTableRow(boolean)
	at com.muwire.gui.MainFrameController.browseFromTrusted(MainFrameController.groovy:458)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:407)
	at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:356)
	at griffon.util.GriffonClassUtils.invokeExactInstanceMethod(GriffonClassUtils.java:3182)
	... 5 more
```

I obviously have no idea why but off the top of my head I can imagine that separating users into Trusted and Distrusted, maybe some reference wasn't updated in all behaviors. Also appears to happen when using the Browse/Browse Collections buttons, not just the context menu.

**Comment by zlatinb** [comment]
Sorry about that, I didn't test browse/browse collections/message after the separation.  Fixed in the latest commit, to be 0.8.13-beta4 which will be available for download in the next half an hour or so.

**Comment by Searinox** [comment]
Went ahead and checked this on beta4, it's fine now.

**Comment by Searinox** [comment]
Resurrecting this one to report exception also on Remove Contact.

**Comment by zlatinb** [comment]
Hi, reported in #161 

I broke a finger on my right hand and it's very hard to type so I will have to look at this in a few weeks, sorry.

**Comment by Searinox** [comment]
Oh sorry man. :S
