### ISSUE TITLE
griffon.core.GriffonExceptionHandler - Uncaught Exception

### ISSUE THREAD

**Issue by ashleysommer** [zlatinb/muwire#16]
Getting this error when I try to launch muwire
OS: Ubuntu 18.04
I've tried MuWire version 0.4.7 and 0.4.11, both give the exact same problem
I've also tried JAVA implemetations: Oracle JDK 1.8, OpenJDK-1.8, and OpenJDK-8, (because I happened to have each of those already installed on my system), it fails with exactly the same message.

```
$> java -Dgriffon.full.stacktrace="true" -jar ./MuWire-0.4.11.jar
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Griffon 2.15.1
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Build: 2018-11-06T14:02:08.126+0100
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - Revision: d5445b6e60e92ba6fe635ce9fe695c4b498f5ae7
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - JVM: 1.8.0_171 (Oracle Corporation 25.171-b11)
[main] INFO org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper - OS: Linux 4.15.0-45-generic amd64
[main] INFO griffon.util.AnnotationUtils - resource bundle loader class with instance org.codehaus.griffon.runtime.util.ClassResourceBundleLoader@20c0a64d evicted by org.codehaus.griffon.runtime.groovy.util.GroovyScriptResourceBundleLoader@455b6df1
Sep 16, 2019 5:22:45 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: Loading home dir
Sep 16, 2019 5:22:45 PM org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod
INFO: will try default lnfs
No protocol specified
Sep 16, 2019 5:22:45 PM org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
WARNING: All Look and Feel options failed: [system, gtk]
[main] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception.
java.lang.NullPointerException: Cannot invoke method getID() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:164)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at Initialize.execute(Initialize.groovy:89)
        at org.codehaus.griffon.runtime.core.DefaultApplicationConfigurer.runLifecycleHandler(DefaultApplicationConfigurer.java:111)
        at org.codehaus.griffon.runtime.core.DefaultApplicationConfigurer.doInitialize(DefaultApplicationConfigurer.java:122)
        at org.codehaus.griffon.runtime.core.DefaultApplicationConfigurer.init(DefaultApplicationConfigurer.java:86)
        at org.codehaus.griffon.runtime.core.AbstractGriffonApplication.initialize(AbstractGriffonApplication.java:264)
        at org.codehaus.griffon.runtime.core.AbstractApplicationBootstrapper.run(AbstractApplicationBootstrapper.java:90)
        at org.codehaus.griffon.runtime.core.AbstractGriffonApplication.run(AbstractGriffonApplication.java:99)
        at griffon.swing.SwingGriffonApplication.main(SwingGriffonApplication.java:78)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at com.muwire.gui.Launcher.main(Launcher.groovy:8)
```

**Comment by zlatinb** [comment]
Hi, what window manager are you using?  The reason this is happening is because the loading of the look-and-feel fails.
To work around this, create a file called `gui.properties` in $HOME/.MuWire and put the following line there:
`lnf=metal`
This will force MuWire to use the "metal" theme which should work.

**Comment by zlatinb** [comment]
In my latest commit I've made it try the "metal" theme if the others fail, even without a `gui.properties` file.  Give that a try if you wish
