### ISSUE TITLE
Deleting Contact kills Muwire

### ISSUE THREAD

**Issue by JamesOlvertone** [zlatinb/muwire#161]
Do this:
Browse a contact from your contact list (this user is not connected to muwire)
delete this contact while trying to browse his files -> crash:

`groovy.lang.MissingMethodException: No signature of method: com.muwire.gui.MainFrameController.removeContact() is applicable for argument types: () values: []
	at com.muwire.gui.MainFrameView$_showContactsMenu_closure82.doCall(MainFrameView.groovy:2323)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

**Comment by zlatinb** [comment]
Thanks for the report I'll take a look as soon as I can.  This should happen only when removing from right click menu; the remove contact button should still work.

**Comment by zlatinb** [comment]
Please try the latest [CI build](https://github.com/zlatinb/muwire/actions/runs/2813014770) this should now work

**Comment by JamesOlvertone** [comment]
yes seems to work.

**Comment by Searinox** [comment]
Fix confirmed.

**Comment by zlatinb** [comment]
Thanks for confirming!
