### ISSUE TITLE
I set the TCP and UDP port in Options, but it change it on next start

### ISSUE THREAD

**Issue by slrslr** [zlatinb/muwire#45]
Hello,

i port forward two ports on router and set these in MuWire 0.6.12 Options. Ports like 12345 and 123456 (TCP and UDP). Save, quit MuWire, start it and i see ports was changed to ones that are filtered (not forwarded), which i think is worse connection. I am on Windows 10.

**Comment by zlatinb** [comment]
123456 isn't a valid port number, did you mean 12346?  Either way, I reproduced it.  Will investigate what's causing it and post an update once I find out.

**Comment by zlatinb** [comment]
I found the bug.  Fix will be in 0.6.14, I will probably release that later today.

**Comment by zlatinb** [comment]
0.6.14 is out, get it at https://muwire.com 
please test and close the ticket if fixed

**Comment by slrslr** [comment]
I have to download that 30MB from site, run the installer and it will keep my previous MuWire configuration? The updater that i have enabled will not update MuWire from 0.6.12 to 0.6.14 ?

**Comment by zlatinb** [comment]
I have not pushed 0.6.14 to the automatic update function, so yes, you will need to download from the site.  It will keep your current MuWire configuration, which is stored in `%APPDATA%\MuWire`.  If you wish to be extra safe, backup the contents of that folder before updating.

The automatic update only downoads the installer through MuWire itself; you still need to execute the installer yourself.  That is intentional.

There are few other changes in 0.6.14 which you should be aware of:
* the executable file is now called MuWire.exe so you may need to change your firewall rules (it should ask you automatically I think).
* I have imposed restrictions on the nicknames; they now cannot include any of the following characters: '"();<>=@$% so if your nickname contained such character you will need to edit MuWire.properties to change it, or the application won't load.

**Comment by slrslr** [comment]
I confirm the issue is fixed.
But i see another possible issue. After upgrade from 0.6.12 to 0.6.14 the Uploads section no longer shows mine shared files as it was before upgrade. The C:\Users\Me\AppData\Roaming\MuWire size looks to be roughly same as before upgrade - 590MB, 66000 files
Maybe if i would downgrade the shared files would be visible, unsure why not visible now in new version 0.6.14... what can i try to make these appear? Problem is that hashing cost me previously maybe 2 days time (alot of data to hash on slow HDD) so i would like to prevent rehasing. Thank you.

**Comment by zlatinb** [comment]
Hmm, you are the second person reporting this so I may have broken something with the loading of shared files.  I will investigate, until then please try downgrading to 0.6.12 or 0.6.13 and let me know if the shared files become visible again.

**Comment by zlatinb** [comment]
Can you try https://muwire.com/MuWire-0.6.14-1.exe and let me know if that loads your shared files?

**Comment by slrslr** [comment]
I tried this 0.6.14-1 and mine shared files not appeared on Uploads tab. I waited like 30 minutes for it to appear. Then i quit and installed MuWire-0.6.12 which is what i initialy had when it hashed my files and the files also not appeared for some minutes, but after maybe 30 minuted i checked back and it appeared. So i do not know if the 30 minutes waiting in 0.6.14-1 was enough. If you wish, let me know and i will gladly try other things etc.

**Comment by zlatinb** [comment]
Thanks for your help.  Lets enable debug logging on 0.6.14-1 and find out what is happening.

1. install 0.6.14-1
2. edit `c:\Program Files (x86)\MuWire\app\1_logging.properties`
3. Add the following two lines at the end of the file:
```
com.muwire.core.level = FINE
com.muwire.core.files.level = FINE
```
4. find the line that starts with `java.util.logging.FileHandler.pattern` and change the value to a file where you want MuWire to log to.  For example:
```
java.util.logging.FileHandler.pattern = c:\\Users\\Me\\MuWire.log
```
note that the path needs to have double \ for this to work.

5. Start MuWire; if you configured the logging correctly the log file should appear immediately.

Then watch in the logfile for messages containing `loaded file` and a path to a shared file.  If you see lines like that coming, then everything is fine and eventually MuWire will load your shared files.  (This is because MuWire throttles loading to 500 files per second to preserve CPU). 

However, if you see log statements at WARNING or SEVERE level, then something is wrong and I will need to look at the log file.

Thanks again, let me know how it works out.

**Comment by slrslr** [comment]
I followed the instructions. The log file is being updated. Interesting is that it is not using my computer time to prefix the log entries..:

> 2020-05-08 21:17:54.571 INFO org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod launching embedded router  
> 2020-05-08 19:18:57.994 INFO org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod initializing I2P socket manager  
> 2020-05-08 19:18:58.203 INFO org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod Loaded myself as mynickname@somestring  

the first line match my computer time, but rest lines are 2 hours back which is confusing

i waited around 30 minutes and then was searching in the log file for "loaded file" and found no match. "Uploads" section does not list any of my files and shows "Shared: 0"
I searched for "ERROR" and "WARNING" only interesting warning is this:

```
WARNING com.muwire.core.connection.Connection writeLoop unhandled exception in writer 
java.io.InterruptedIOException: Interrupted write
	at net.i2p.client.streaming.impl.MessageOutputStream.write(MessageOutputStream.java:172)
	at java.base/java.util.zip.DeflaterOutputStream.flush(Unknown Source)
	at java.base/java.io.DataOutputStream.flush(Unknown Source)
	at com.muwire.core.connection.PeerConnection.write(PeerConnection.groovy:79)
	at com.muwire.core.connection.Connection.writeLoop(Connection.groovy:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at com.muwire.core.connection.Connection$_closure2.doCall(Connection.groovy:68)
	at com.muwire.core.connection.Connection$_closure2.doCall(Connection.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.run(Closure.java:499)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at net.i2p.client.streaming.impl.Connection.packetSendChoke(Connection.java:246)
	at net.i2p.client.streaming.impl.PacketLocal.waitForAccept(PacketLocal.java:323)
	at net.i2p.client.streaming.impl.MessageOutputStream.write(MessageOutputStream.java:170)
	... 26 more
```

**Comment by zlatinb** [comment]
The two-hour time difference is most probably because once the embedded router is launched it syncs to UTC and switches the timezone of the process.

Now onto the main issue - why it isn't loading any files.  Do you see a sequence in the log that looks like this:
```
2020-05-08 17:53:05.924 FINE org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod publishing event seqNo 0 timestamp 1588960385922 of type UILoadedEvent event seqNo 0 timestamp 1588960385922  
2020-05-08 17:53:05.979 FINE com.muwire.core.EventBus publishInternal publishing event seqNo 1 timestamp 1588960385976 of type PersisterDoneEvent event seqNo 1 timestamp 1588960385976  
2020-05-08 17:53:05.979 INFO org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod Old persister done  
2020-05-08 17:53:05.980 FINE org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod Loading...
```

That is, an `UILoadedEvent` followed by `PersisterDoneEvent`.  Sequence numbers may be different, timestamps will definitely be different.

Also, is there anything on SEVERE level?  It's not called ERROR.

**Comment by slrslr** [comment]
yes, i see the similar sequences in the log:

```
2020-05-08 19:19:39.661 FINE org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod publishing event seqNo 0 timestamp numberhere of type UILoadedEvent event seqNo 0 timestamp numberhere 
2020-05-08 19:19:40.175 INFO com.muwire.core.connection.ConnectionEstablisher connect starting connect to addresshere.b32.i2p  
2020-05-08 19:19:40.439 FINE com.muwire.core.EventBus publishInternal publishing event seqNo 1 timestamp numberhere of type PersisterDoneEvent event seqNo 1 timestamp numberhere 
2020-05-08 19:19:40.452 INFO org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod Old persister done  
2020-05-08 19:19:40.453 FINE org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod Loading...  
```

following phrases are only once in the file:
FINE org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod publishing event seqNo
FINE org.codehaus.groovy.vmplugin.v7.IndyInterface selectMethod Loading...  

SEVERE was not found

**Comment by zlatinb** [comment]
This is really puzzling, it should start loading the files immediately after that statement.  The thread that does that is set to run with lowest priority, if there is something using up all the system cpu then it might get stuck and not run for a long time.

Few other questions:
* is there a mention of `AllFilesLoadedEvent` being published in the log?
* is there a directory called `files` in `AppData\Roaming\MuWire` ?  It should have many sub-directories, and inside those directories there should be at least two files with the same name, one with extension `.json` and one with `.hashlist`.  Does the user that you run MuWire with have read permissions to those files?

**Comment by slrslr** [comment]
Problem with not appearing shared files (Uploads section) in new version seems to be SOLVED. The reason may be that my Antivirus (Comodo Internet Security) automaticaly contained the new app (i think i recently enabled this feature) and i was not aware about that it is there and breaks data saving/loading. When i disabled that antivirus feature, now the shared files appears. So there are no longer issues.

If MuWire is made to report to the user or in the log that it is unable to access some required files, maybe. The issue would be easier to find the cause.
