### ISSUE TITLE
Very poor UI responsiveness while sharing large files

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#84]
This must have started some time during the new build releases.

The setup involves hashing a series of large, multi-GB files. At the same time, another user is downloading a(different) large file from the instance in question. I am not sure to what extent this is contributing but I am mentioning it here.

The interface is being very unresponsive. It is accepting a click every ~30 seconds, I think in between finishing sharing a file and moving on to the next one. I tabbed out of the Library but the issue persists no matter where I am.

**Comment by zlatinb** [comment]
Hmm, the hashing should be completely independent from the UI thread.  You can fetch a stack by using the `jstack` command from a command prompt.  First get the process id of the MuWire process with `jps`, then pass that value to `jstack`.

The stack trace will print all threads; the one you're interested in is called `AWT-EventQueue-0` .  Try to hit jstack exactly while the UI is unresponsive, that will show us what is going on.

**Comment by Searinox** [comment]
As we speak the thread is still looping and the UI remains frozen so this should catch the bug in the act. Here's what I got:

"AWT-EventQueue-0" #21 prio=6 os_prio=0 cpu=6382812.50ms elapsed=18904.32s tid=0x00000167ffa1d800 nid=0x4214 runnable  [0x00000037266fb000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.AbstractStringBuilder.append(java.base@11.0.12/Unknown Source)
	at java.lang.AbstractStringBuilder.append(java.base@11.0.12/Unknown Source)
	at java.lang.StringBuilder.append(java.base@11.0.12/Unknown Source)
	at sun.text.normalizer.Norm2AllModes$NoopNormalizer2.normalize(java.base@11.0.12/Unknown Source)
	at sun.text.normalizer.NormalizerBase.nextNormalize(java.base@11.0.12/Unknown Source)
	at sun.text.normalizer.NormalizerBase.next(java.base@11.0.12/Unknown Source)
	at java.text.CollationElementIterator.next(java.base@11.0.12/Unknown Source)
	at java.text.RuleBasedCollator.compare(java.base@11.0.12/Unknown Source)
	- locked <0x000000041e800098> (a java.text.RuleBasedCollator)
	at java.text.Collator.compare(java.base@11.0.12/Unknown Source)
	at javax.swing.DefaultRowSorter.compare(java.desktop@11.0.12/Unknown Source)
	at javax.swing.DefaultRowSorter$Row.compareTo(java.desktop@11.0.12/Unknown Source)
	at javax.swing.DefaultRowSorter$Row.compareTo(java.desktop@11.0.12/Unknown Source)
	at java.util.ComparableTimSort.mergeLo(java.base@11.0.12/Unknown Source)
	at java.util.ComparableTimSort.mergeAt(java.base@11.0.12/Unknown Source)
	at java.util.ComparableTimSort.mergeCollapse(java.base@11.0.12/Unknown Source)
	at java.util.ComparableTimSort.sort(java.base@11.0.12/Unknown Source)
	at java.util.Arrays.sort(java.base@11.0.12/Unknown Source)
	at javax.swing.DefaultRowSorter.sort(java.desktop@11.0.12/Unknown Source)
	at javax.swing.DefaultRowSorter.allRowsChanged(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JTable.notifySorter(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JTable.sortedTableChanged(java.desktop@11.0.12/Unknown Source)
	at javax.swing.JTable.tableChanged(java.desktop@11.0.12/Unknown Source)
	at javax.swing.table.AbstractTableModel.fireTableChanged(java.desktop@11.0.12/Unknown Source)
	at javax.swing.table.AbstractTableModel.fireTableDataChanged(java.desktop@11.0.12/Unknown Source)
	at javax.swing.table.AbstractTableModel$fireTableDataChanged.call(Unknown Source)
	at com.muwire.gui.MainFrameView.refreshSharedFilesTable(MainFrameView.groovy:1951)
	at com.muwire.gui.MainFrameView$refreshSharedFilesTable$2.call(Unknown Source)
	at com.muwire.gui.MainFrameModel$_onUploadEvent_closure13.doCall(MainFrameModel.groovy:611)
	at com.muwire.gui.MainFrameModel$_onUploadEvent_closure13.doCall(MainFrameModel.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor1017.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.12/Unknown Source)
	at java.lang.reflect.Method.invoke(java.base@11.0.12/Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventQueue$4.run(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventQueue$4.run(java.desktop@11.0.12/Unknown Source)
	at java.security.AccessController.doPrivileged(java.base@11.0.12/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.12/Unknown Source)
	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.12/Unknown Source)
	at java.awt.EventDispatchThread.run(java.desktop@11.0.12/Unknown Source)

**Comment by zlatinb** [comment]
Ok, what this stack trace tells me is that the library table is sorted by some column and that it's stuck sorting because a new upload was started.  Approximately how many files are you sharing?  The performance of the UI will be affected by the number of files, not by their size.

**Comment by zlatinb** [comment]
I can speed up the sorting process significantly by using a "stupid" string comparator, one that doesn't obey locale sorting rules.  Some may see it as a regression though.

**Comment by Searinox** [comment]
I did as you asked. At the time of clicking, it had only loaded around 4000 files into the Library. As soon as I clicked the Name column to sort, MuWire became fully unresponsive and did not respond to my attempt to switch to another tab. After a long time it finally switched to that tab but remained largely unresponsive, even though it was no longer onscreen.

If I may remind you of another idea, you made several tabs stop updating the list while unfocused and that at least made the application responsive while not in the affected tab - in this case Library. I can see use for it here as well.

**Comment by zlatinb** [comment]
Ok, partially implemented in 84-2; more specifically the library UI gets updated once a second regardless of tab order.  Let's see how that behaves in the test case and if it's still slow I'll implement not updating unless the tab is visible.

https://muwire.com/downloads/MuWire-0.8.9-GitHub84-2.zip
